[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_py"
version = "0.6.0"
dependencies = [
	"requests",
   	'importlib-metadata; python_version>"3.10"',
]

[tool.setuptools]
packages = ["my_resources",
			"my_files",
			"my_plot",
			"my_math",
			"my_series",
			"my_gridded",
			"my_misc",
			"my_science",
			"my_data",]
package-dir = {"" = "src"}
