[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_py"
version = "0.5.0"
dependencies = [
	"requests",
   	'importlib-metadata; python_version>"3.10"',
]

[tool.setuptools]
packages = ["my_resources", "my_files", "my_plot", "my_math", "my_series", "my_data_process", "my_gridded", "my_misc"]
package-dir = {"" = "src"}
